# Generated by Django 6.1.1 on 2026-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='media/blog_img'),
        ),
    ]
