# Generated by Django 6.1.1 on 2026-10-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogmodel_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
